version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"


  web:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: f3d3d21a5b91fbd29f34e05d6f7b6d8f348b8c5b7a91eae90e4e5b7636f7d7
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
