
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>




development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

  

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

  

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>


